socks:
  image: busybox
  volumes:
    - /socks
    - /pids

db:
  image: postgres
  ports:
    - "5432"

redis:
  image: redis

sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - db
    - redis
  environment:
    REDIS_URL: redis://redis:6379

app:
  build: .
  command: bundle exec unicorn -c config/unicorn.rb -l /socks/unicorn.todo.sock
  volumes:
    - .:/app
  volumes_from:
    - socks
  links:
    - db
    - redis
  environment:
    REDIS_URL: redis://redis:6379

web:
  build: container/nginx
  ports:
    - "80:80"
  volumes_from:
    - app
    - socks
